src/objects/Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RelatedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hidden Relationships List</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coworker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acquaintance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Niece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wife</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RelationshipViewerController.cls
global with sharing class RelationshipViewerController {
    
    global RelationshipViewerController(ApexPages.StandardController controller) {
	}  

    @RemoteAction
    global static list<Node> getRelationships(id cid) {
        list<Node> returnList = new list<Node>();
        list<Relationship__c> relationshipList = new list<Relationship__c>();
		
        //base node
        Node basenode = new Node();
      
        Contact c = [select LastName, FirstName, id, Title, Account.Name from Contact where id = :cid];
        basenode.LastName = c.LastName;
        basenode.FirstName = c.FirstName;
        basenode.Title = c.Title;
        basenode.AccountName = c.Account.Name;
        basenode.id = c.id;
        returnList.add(basenode);
        
        relationshipList = [select id, RelatedContact__r.LastName, Type__c, Status__c, RelatedContact__r.FirstName, RelatedContact__r.id, RelatedContact__r.Account.Name, RelatedContact__r.Title from Relationship__c where Contact__c = :cid];

        for (Relationship__c r : relationshipList){
        	Node n = new Node();
        	n.LastName = r.RelatedContact__r.LastName;
        	n.id = r.RelatedContact__r.id;
        	n.Type = r.Type__c;
        	n.Status = r.Status__c;
        	n.FirstName = r.RelatedContact__r.FirstName;
        	n.link =  URL.getSalesforceBaseUrl().toExternalForm() + '/' + r.RelatedContact__r.id;
        	n.AccountName = r.RelatedContact__r.Account.Name;
        	n.Title = r.RelatedContact__r.Title;
			
        	returnList.add(n);
        	
        }

        return returnList;
    }

    global class Node { 
    	string FirstName;
        string LastName;
        string id;            	
    	string Status;
    	string Type;
    	string link; 	
    	string AccountName;
    	string Title;
    }  

}